project:
  type: website
  resources:
    - "assets/**/*"

website:
  title: ""
  page-navigation: true
  favicon: assets/img/CERISE_round.png
  site-path: website/
  navbar:
    logo: assets/img/CERISE_BackgroundTransparent.png

    left:
      - text: "The Project"
        href: index.qmd

      - text: "Initiatives"
        href: green-skills-initiatives.qmd
        
      - text: "Resources"
        href: green-skills-resources.qmd
  page-footer:
    border: true
    background: light
    center: |
      :::{.grid}
      ::::{.g-col-2}
      ![](/assets/img/1680161519-kl-EN Co-funded by the EU_POS.jpg){.footer-logo fig-alt="EU Logo"}
      ::::
      ::::{.g-col-10}
      Co-funded by the European Union. All rights reserved.
      <br />Views and opinions expressed are those of the author(s) only and do not necessarily reflect those of the European Union or European Education and Culture Executive Agency (EACEA).
      Neither the European Union nor the granting authority can be held responsible for them.
      ::::
      :::

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
#      - text: "News"
#        href: news.qmd

#      - text: "Contribute"
#        href: contribute.qmd


  # sidebar:
  #   - title: "Home"
  #     style: "docked"
  #     contents:
  #       - index.qmd

  #   - title: "About"
  #     contents:
  #       - about.qmd        

  #   - title: "Initiatives"
  #     contents:
  #       - green-skills-initiatives.qmd

  #   - title: "Resources"
  #     contents:
  #       - green-skills-resources.qmd