project:
  type: website
  resources:
    - "assets/**/*"

website:
  title: ""
  page-navigation: true
  favicon: assets/img/CERISE_round.png
  navbar:
    logo: assets/img/CERISE_BackgroundTransparent.png

    left:
      - text: "The Project"
        href: index.qmd

      - text: "Initiatives"
        href: green-skills-initiatives.qmd
        
      - text: "Resources"
        href: green-skills-resources.qmd
  
  page-footer:
   left: |
      <div class="footer-left-inline">
      <img src="assets/img/1680161519-kl-EN Co-funded by the EU_POS.jpg" alt="EU logo" class="footer-logo">
      <span class="footer-text">
            Co-funded by the European Union. All rights reserved. Funded by the European Union.
            Views and opinions expressed are those of the author(s) only and do not necessarily
            reflect those of the European Union or European Education and Culture Executive Agency (EACEA).
            Neither the European Union nor the granting authority can be held responsible for them.
      </span>
      </div>

      

format:
  html:
    css: assets/css/styles.css
#      - text: "News"
#        href: news.qmd

#      - text: "Contribute"
#        href: contribute.qmd


  # sidebar:
  #   - title: "Home"
  #     style: "docked"
  #     contents:
  #       - index.qmd

  #   - title: "About"
  #     contents:
  #       - about.qmd        

  #   - title: "Initiatives"
  #     contents:
  #       - green-skills-initiatives.qmd

  #   - title: "Resources"
  #     contents:
  #       - green-skills-resources.qmd