project:
  type: website
  resources:
    - "assets/**/*"

website:
  title: ""
  page-navigation: true
  favicon: assets/img/CERISE_round.png
  navbar:
    logo: assets/img/CERISE_BackgroundTransparent.png

    left:
      - text: "The Project"
        href: index.qmd

      - text: "Initiatives"
        href: green-skills-initiatives.qmd
        
      - text: "Resources"
        href: green-skills-resources.qmd
  
#      - text: "News"
#        href: news.qmd

#      - text: "Contribute"
#        href: contribute.qmd


  # sidebar:
  #   - title: "Home"
  #     style: "docked"
  #     contents:
  #       - index.qmd

  #   - title: "About"
  #     contents:
  #       - about.qmd        

  #   - title: "Initiatives"
  #     contents:
  #       - green-skills-initiatives.qmd

  #   - title: "Resources"
  #     contents:
  #       - green-skills-resources.qmd

format:
  html:
    theme: cosmo
    css: assets/css/styles.css
    toc: false
