---
title: "CERISE: Capacity building and technologies for Green skills orientedness at European Universities"
---




The general objective of the project is strengthening capacity of European Higher Education Institutions (HEIs) in delivering courses and services that enhance and recognize green skills and expand green culture. 

**Specific objective 1**: Support HE curricula development to advance HE students’ green skills and attitudes through digital technologies.  

**Specific objective 2:** Develop a technological tool that will foster the recognition of green skills in the HE sector. 


---

 - **Project no.:** 2023-2-LU01-KA220-HED-000178778
 - **Project funding:** The European Union programme Erasmus+
 - **Period of project implementation:** 2024-02-01 - 2026-05-31
 - **Project coordinator:** [University of Luxembourg (UniLu)](https://www.uni.lu/en/){.external target="_blank"}
 - **Project partners:** 
   - [Web2Learn](https://www.web2learn.eu){.external target="_blank"}
   - [National Technical University of Athens (NTUA)](https://www.ntua.gr){.external}
   - [Université de Lorraine (UL)](https://www.univ-lorraine.fr){.external target="_blank"}
   - [University of Information Technology and Management in Rzeszów (UITM)](https://www.wsiz.rzeszow.pl){.external target="_blank"}
   - [Kaunas University of Technology (KTU)](https://en.ktu.edu/projects/capacity-building-and-technologies-for-green-skills-orientedness-at-european-universities-cerise/){.external target="_blank"}

