## Discovering careers in the Ecological Transition, creating jobs
### Description

This MOOC aims to offer an overview of careers in the ecological transition through testimonials from professionals and their associated training pathways. Its goal is to provide a better understanding of the highly diverse fields, the various careers that the ecological transition encompasses, and the different training paths to access them, with the ambition of helping students better orient themselves.

### Type of Initiative

MOOC

### Provider

UVED (Environment and Sustainable Development Virtual University) 

### Creator

nan

### description

This MOOC aims to offer an overview of careers in the ecological transition through testimonials from professionals and their associated training pathways. Its goal is to provide a better understanding of the highly diverse fields, the various careers that the ecological transition encompasses, and the different training paths to access them, with the ambition of helping students better orient themselves.

### language

French

### url_initiative

https://www.uved.fr/mooc-metiers-te

### resources

46 videos / Course sheet

### url_resources

https://www.uved.fr/fiche/parcours/les-metiers-de-la-transition-ecologique-creatrice-demplois/1/approfondi#sequence

https://www.uved.fr/fileadmin/user_upload/Documents/pdf/Fiche-MOOC_MetiersTE-3.pdf

### target_audience

Students

### type

MOOC

### thematic_focus

Sustainable business practice, Vocational guidance

### green_skill_specificity_level

Transversal, Domain specific 

### location

MOOC (FUN Mooc) + once the sessions have ended, outside the MOOC context and independently of a platform, all the videos are freely available (UVED)

### content

Introduction: Ecological reconversion
Week 1: Definition, general dynamics and attractiveness of jobs in the Ecological Transition
Week 2: Discovering careers and training by sector of activity
Week 3: Examples of collaborative, multi-disciplinary projects linked to the Ecological Transition.

### duration

Duration: 4 weeks
Effort: 8 hours
Pace: 2 hours/week

### cost

Free

### end_date

The 5th session ended on June 30, 2024

### impact

27490 registred particpants in total (since 2020) 

### provider_name

UVED (Environment and Sustainable Development Virtual University) 

### provider_type

Fondation

### funded_by

The French government as part of the “Territoires d'innovation pédagogique” program, operated by Caisse des Dépôts.

### recommendations

- testimonials from professionals
- provide guidance for career choices

