## Edinburgh Earth Initiative
### Description

The Edinburgh Earth Initiative is accelerating the University of Edinburgh’s response to the climate crisis. Working with our academics, students, staff, and partners, we help ensure the University of Edinburgh is at the leading edge of climate research, teaching, innovation and action.
We drive resources towards core research on ecosystems, energy futures, and health; we create opportunities to train future leaders through scholarships and fellowships; we help to foster innovations that deliver real-world impacts on climate mitigation and adaptation; we help ensure that climate and environmental is central to our international partnerships; we work to make academic knowledge available to decision makers in business, industry, policymaking institutions, regulatory authorities, and civil society organisations; and we put climate justice at the centre of our institutional commitments. 

### Type of Initiative

Educational Program

### Provider

University of Edinburgh

### Creator

nan

### description

The Edinburgh Earth Initiative is accelerating the University of Edinburgh’s response to the climate crisis. Working with our academics, students, staff, and partners, we help ensure the University of Edinburgh is at the leading edge of climate research, teaching, innovation and action.
We drive resources towards core research on ecosystems, energy futures, and health; we create opportunities to train future leaders through scholarships and fellowships; we help to foster innovations that deliver real-world impacts on climate mitigation and adaptation; we help ensure that climate and environmental is central to our international partnerships; we work to make academic knowledge available to decision makers in business, industry, policymaking institutions, regulatory authorities, and civil society organisations; and we put climate justice at the centre of our institutional commitments. 

### language

English

### url_initiative

https://earth.ed.ac.uk/

### resources

Guidelines, Interactive map

### url_resources

https://earth.ed.ac.uk/nbl-guidelines/
https://earth.ed.ac.uk/outdoor-learning-sites/

### target_audience

Students, Teacher, Administrative Staff

### type

Educational Program

### thematic_focus

Waste Management, Renewable Energy, Sustainable Transportation, Energy Efficiency, Water Management, Sustainable Agriculture, Biodiversity Conservation, Urban Planning, Green Building, Environmental Education and Awareness, Sustainable Business Practices, Policy and Governance, Community Engagement and Outreach

### green_skill_specificity_level

Transversal

### location

University of Edinburgh, On-campus and Online

### provider_name

University of Edinburgh

### provider_type

University

### funded_by

The Edinburgh Earth Initiative is funded by the University of Edinburgh and external supporters

### recommendations

- The Mapping Green Infrastructure story map promotes and faciliates outdoor teaching

