## EU GREEN
### Description

EU GREEN (responsible GRowth, inclusive Education and ENvironment) is a transnational Alliance of nine European universities aiming to be a Gateway to Sustainability. The project’s goal is to create a broad European educational area through strengthening and disseminating European values where sustainability is a transversal element. Some of the project activities include creation of pedagogical methodologies and university staff training, research clusters, promotion of entrepreneurship, innovation and mobility in relation to sustainability, community engagement, and others. The project also promotes a participatory methodology to involve the whole academic world (academic staff, non-academic staff and students) in environmental and social challenges and to stimulate behavioural change of all actors towards more sustainable practices.  

### Type of Initiative

Network

### Provider

EU GREEN

### Creator

University of Gävle (Sweden), Wroclaw University of Environmental and Life Sciences (Poland), Universitá di Parma (Italy), Université D’Angers (France), Universidade de Évora (Portugal), Otto von Guericke Universität Magdeburg (Germany), Atlantic Technological University (Ireland), Universitatea Din Oradea (Romania), and Universidad de Extremadura (Spain).

### description

EU GREEN (responsible GRowth, inclusive Education and ENvironment) is a transnational Alliance of nine European universities aiming to be a Gateway to Sustainability. The project’s goal is to create a broad European educational area through strengthening and disseminating European values where sustainability is a transversal element. Some of the project activities include creation of pedagogical methodologies and university staff training, research clusters, promotion of entrepreneurship, innovation and mobility in relation to sustainability, community engagement, and others. The project also promotes a participatory methodology to involve the whole academic world (academic staff, non-academic staff and students) in environmental and social challenges and to stimulate behavioural change of all actors towards more sustainable practices.  

### language

English

### url_initiative

https://eugreenalliance.eu/

### resources

e.g., EU GREEN Blended Intensive Programmes (BIPs)

### url_resources

https://eugreenalliance.eu/eu-green-blended-intensive-programmes-bips/

### target_audience

Students, Teachers

### type

Network

### thematic_focus

Environmental Education and Awareness, Sustainable Business Practices, Policy and Governance, Community Engagement and Outreach

### location

EU GREEN website and sites of 9 universities across the EU

### content

EDUCATION: Creation of a specific Pedagogical and Professional Development Programme for teaching and non-academic staff, with the participation of experts in the field;
Organisation of annual teaching concentrations for teaching staff and Staff Weeks for non-academic staff;
Creation of a library of pedagogical methodologies.

INNOVATION AND ENTREPRENEURSHIP: Promotion of entrepreneurship, supporting the creation of start-ups and spin-offs focused on sustainability-related products/services. These activities will include:
summer camps for entrepreneurs, training activities to prepare doctoral students and research staff in sustainable entrepreneurship, a physical space associated to the EU GREEN project in each University (EU GREEN Business Lounges)...


### impact

158
k students

### creator_name

University of Gävle (Sweden), Wroclaw University of Environmental and Life Sciences (Poland), Universitá di Parma (Italy), Université D’Angers (France), Universidade de Évora (Portugal), Otto von Guericke Universität Magdeburg (Germany), Atlantic Technological University (Ireland), Universitatea Din Oradea (Romania), and Universidad de Extremadura (Spain).

### creator_role

Consortium

### provider_name

EU GREEN

### contact_email

info@eugreenalliance.eu 

### funded_by

European Union´s Erasmus+ Programme (Grant Agreement nº 101089896)

### funding_amount

14.4 million euros

### recommendations

- In the future, creation of an EU GREEN European Virtual University
- Promotion of entrepreneurship, supporting the creation of start-ups and spin-offs focused on sustainability-related products/services.


