## EUSTEPs (Enhancing Universities’ Sustainability TEaching and Practices)
### Description

EUSTEPs aims to educate European university students and the wider academic community about the complexity of sustainability and its interdisciplinary nature in an engaging and captivating manner.
In addition, its goal is to support the assessment and reduction of the environmental impact of EU Higher Education Institutions (HEIs) through an experiential approach based on an innovative application of the Ecological Footprint. The key outputs of the EUSTEPs project are:
E-learning Platform & University Footprint Calculator

### Type of Initiative

nan

### Provider

EUSTEPs

### Creator

Aristotle University of Thessaloniki, Greece
University of Aveiro, Portugal
Universidade Aberta, Portugal
University of Siena, Italy


### description

EUSTEPs aims to educate European university students and the wider academic community about the complexity of sustainability and its interdisciplinary nature in an engaging and captivating manner.
In addition, its goal is to support the assessment and reduction of the environmental impact of EU Higher Education Institutions (HEIs) through an experiential approach based on an innovative application of the Ecological Footprint. The key outputs of the EUSTEPs project are:
E-learning Platform & University Footprint Calculator

### language

English, Italian, Greek, Portuguese

### url_initiative

https://www.eusteps.eu/

### resources

Mooc, Teaching material, Footprint calculator

### url_resources

https://www.eusteps.eu/resources/student-educator-teaching-material/
https://aulaberta.uab.pt/blocks/catalog/detail.php?id=59
https://eusteps.footprintcalculator.org/

### target_audience

Students, Teachers,Staff

### thematic_focus

Nature and Environment
Sustainability 
Ecological Footprint 
Higher Education Institutions 

### content

The MOOC allows you to acquire knowledge on the concept of sustainability and the Ecological Footprint, by using examples and contexts from real life. It also helps you to understand what approaches can you make to address the global sustainability issue.
Topic 1 - Introduction to Ecological Overshoot, Sustainability, and SDGs
Topic 2 - Connecting your daily life with SDGs
Topic 3 - Introduction to Ecological Footprint
Topic 4 - Your Personal Ecological Footprint
Topic 5 - HEI: Sustainability aspects and assessment tools
Topic 6 - HEI: Sustainability best practices

### duration

50 hours overall, corresponding to approximately 7 hours per week.


### cost

Free

### creator_name

Aristotle University of Thessaloniki, Greece
University of Aveiro, Portugal
Universidade Aberta, Portugal
University of Siena, Italy


### provider_name

EUSTEPs

### contact_email

gmalandrakis@eled.auth.gr

