## Green Skills for Jobs and Entrepreneurship
### Description

Green Skills for Jobs and Entrepreneurship is an award winning, transformational programme delivered by the University of the West of England (UWE Bristol) designed to support young people from Black, Asian and racially minoritised backgrounds into the emerging Green Sector. 
The key objectives of the Green Skills programme are:
To support a just and inclusive transition to a green economy;
To close the skills gap between job opportunities and young people; and
To tackle the underrepresentation of people from minoritised backgrounds in environmental careers, recognising that the sector is the second least diverse in the UK.

### Type of Initiative

nan

### Provider

nan

### Creator

University of the West of England (UWE Bristol)

### description

Green Skills for Jobs and Entrepreneurship is an award winning, transformational programme delivered by the University of the West of England (UWE Bristol) designed to support young people from Black, Asian and racially minoritised backgrounds into the emerging Green Sector. 
The key objectives of the Green Skills programme are:
To support a just and inclusive transition to a green economy;
To close the skills gap between job opportunities and young people; and
To tackle the underrepresentation of people from minoritised backgrounds in environmental careers, recognising that the sector is the second least diverse in the UK.

### language

English

### url_initiative

https://www.greenskillsforjobs.co.uk/

### content

 An overview of the topics that will be covered is listed below:

- Introduction 
- Introduction to the Green Economy
- Enterprise and the Green Economy
- Food, Living and the Circular Economy
- Renewable Energy
- Seeds of Change
- Innovation
- Careers and Enterprise in the Green Sector.

### cost

The programme offers an 'earn-while-you-learn' opportunity, paying young people the Real Living Wage (£10.90 per hour) for eight days of skills training, where they will receive tailored coaching, mentoring and career advice and the opportunity to network with industry professionals and community leaders. The programme also offers access to paid internships or paid support to work on business or social enterprise start-up ideas.

### impact

supported and remunerated 90 young people

### creator_name

University of the West of England (UWE Bristol)

### contact_name

 greenskills@uwe.ac.uk

