## Green skills for education: promoting environmental awareness and sustainable actions in the classroom.
### Description

This training course allows participants to get a deeper insight and sharing of the role teachers and education can play in promoting a green skill set and a learning environment responsive to the most topical global challenges. Participants will learn and practice tools and strategies to model conscious behaviors, promote dialogue and debate among students on climate change, plan lessons around sustainable development goals. The general aim of this course is to equip teachers and education staff with formal, informal and non-formal tools to become active players in the green transition, developing students green skills and promoting a behavioral change in favor of a true commitment to sustainable development goals.

### Type of Initiative

Training

### Provider

Erasmus Learning Academy (ELA)

### Creator

nan

### description

This training course allows participants to get a deeper insight and sharing of the role teachers and education can play in promoting a green skill set and a learning environment responsive to the most topical global challenges. Participants will learn and practice tools and strategies to model conscious behaviors, promote dialogue and debate among students on climate change, plan lessons around sustainable development goals. The general aim of this course is to equip teachers and education staff with formal, informal and non-formal tools to become active players in the green transition, developing students green skills and promoting a behavioral change in favor of a true commitment to sustainable development goals.

### language

English

### url_initiative

https://www.erasmustrainingcourses.com/green-skills.html

### resources

Course sheet

### url_resources

https://drive.google.com/file/d/1_ZLF6CGx9GDoiO-bQJrKnfJJdv7jAt96/view  

### target_audience

Teachers

### type

Training

### thematic_focus

Environmental Education and Awareness

### green_skill_specificity_level

Transversal

### location

Physical location (Bologna, Tenerife, Palermo, Porto, Thessaloniki)

### content

e.g., 
- Introduction to the pyramid of green skills
- Teaching hard green skills in the classroom: the Agenda 2030 and SDGs
- Taking action: creating your green action plans at the personal and classrom/school levels...

### duration

1 week

### cost

Depends on the location (From 1225 to 1405 EUR)
Erasmus Grant possible

### provider_name

Erasmus Learning Academy (ELA)

### provider_type

Teacher Training centre 

### contact_email

info@erasmuslearningacademy.eu

### funded_by

European Union

### recommendations

- Provide teachers tools for promotting green skills
- Although adaptable to different teaching levels, more appropriate for primary and secondary education?

