## Green Campus
### Description

The main objective of this project is to support the promotion of sustainable and healthy lifestyles for university campuses and their stakeholders.
By providing awareness, guidance, and support to the young new leaders of sport, we aspire them to be part of the necessary change to promote sustainability and healthy habits.

### Type of Initiative

nan

### Provider

SportAcademy

### Creator

European Network of Academic Sports Services (BEL) in
partnership with Sport Evolution Alliance (POR), European Network for Innovation and Knowledge (NLD),
International University Sports Federation (CHE),
Universidad Pablo D’Olavide (ESP) and CuiCui (ESP).

### description

The main objective of this project is to support the promotion of sustainable and healthy lifestyles for university campuses and their stakeholders.
By providing awareness, guidance, and support to the young new leaders of sport, we aspire them to be part of the necessary change to promote sustainability and healthy habits.

### language

English

### url_initiative

https://www.greencampusproject.eu/

### resources

Courses

### url_resources

https://sportacademy.app/courses/green-campus/

### target_audience

Teachers, Other

### content

The online course is targeted at university professors and campus managers, dedicated to raising awareness of the need of these strategies and to provide a basis of knowledge to encourage their implementation in different universities. Comprising six modules covering various related topics in:
Module 1. Introduction to Green Campus
Module 2. Glossary to Green Campus
Module 3. Physical Activity, Sport and Sustainability
Module 4. Sustainability and Innovation
Module 5. Sustainable and effective communication for Green Campus
Module 6. The Green Campus Label
Final Assignment: Build your own Green Campus Good Practice

### creator_name

European Network of Academic Sports Services (BEL) in
partnership with Sport Evolution Alliance (POR), European Network for Innovation and Knowledge (NLD),
International University Sports Federation (CHE),
Universidad Pablo D’Olavide (ESP) and CuiCui (ESP).

### provider_name

SportAcademy

### funded_by

Erasmus+ Sport Project, funded
by the European Union

### recommendations

There is an app with best practices and a questionnaire to evaluate your university (green campus management - physical activity and sport - nature, environemnt and sustainability)

