## Green Digital Skills
### Description

The INCO Academy Green Digital Skills Certificate program will empower you with the necessary knowledge and practices to act with sustainability and green design in mind.
By the end, you’ll have the in-demand skills to help future-proof your digital career for a greener future.

### Type of Initiative

nan

### Provider

INCO Academy

### Creator

nan

### description

The INCO Academy Green Digital Skills Certificate program will empower you with the necessary knowledge and practices to act with sustainability and green design in mind.
By the end, you’ll have the in-demand skills to help future-proof your digital career for a greener future.

### language

English, French, Polish, Spanish, Greek, Indonesia, Portuguese

### url_initiative

https://www.greenskills.inco-group.co/

### target_audience

Students

### location

Website

### content

Module 1: Foundations of Sustainability in Tech
Module 2: Green Design Principles & Practices
Module 3: Your Journey to Green & Greening Careers


### duration

18-25 hours (to be completed within 5 weeks)

### cost

Free

### provider_name

INCO Academy

### funded_by

Microsoft and LinkedIn 

### recommendations

upskill individuals with sustainability and green design in mind.

