## Greenentre4future
### Description

The GreenEntre4Future project aims to involve and train Youth Workers through the following objectives:
Define sustainable development approaches;
Develop and share tools to empower youth;
Train youth workers;
To promote initiatives for the European climate legislation;
To create synergy among stakeholders.
They propose a MOOC (Massive Open Online Course) to lead youth in green market to seize job opportunities and to create synergies and collaboration in green sector.

### Type of Initiative

MOOC

### Provider

Greenentre4future

### Creator

 Cross Culture International Foundation Cyprus, Pafos (Cyprus) – parceiro
Coordenador
 Infinitivity Design Labs, Laussone (France)
 Petit Pas, Trani (Italy)
 União das Freguesias de Gondomar (S. Cosme), Valbom e Jovim (Portugal)
 Lidi Smart Solutions, The Hague, (Holanda)

### description

The GreenEntre4Future project aims to involve and train Youth Workers through the following objectives:
Define sustainable development approaches;
Develop and share tools to empower youth;
Train youth workers;
To promote initiatives for the European climate legislation;
To create synergy among stakeholders.
They propose a MOOC (Massive Open Online Course) to lead youth in green market to seize job opportunities and to create synergies and collaboration in green sector.

### language

English, Portuguese, Italian, Greek, French, Dutch

### url_initiative

http://www.greenentre4future.eu/

### resources

Mooc

### url_resources

https://mooc.greenentre4future.eu/

### target_audience

The project is addressed at strengthening and validating competences of youth, future start uppers, young entrepreneurs, NEET, youth workers, trainers, experts, educators, staff, stakeholders (policymakers, green businesses, consumers) for environmental change, support investments and related growth.

### type

MOOC

### location

Online

### content

Unit 1. Green management
Unit 2. Digital marketing
Unit 3. Legal literacy
Unit 4: Financial literacy
Unit 5: Communication





### cost

Free

### creator_name

 Cross Culture International Foundation Cyprus, Pafos (Cyprus) – parceiro
Coordenador
 Infinitivity Design Labs, Laussone (France)
 Petit Pas, Trani (Italy)
 União das Freguesias de Gondomar (S. Cosme), Valbom e Jovim (Portugal)
 Lidi Smart Solutions, The Hague, (Holanda)

### provider_name

Greenentre4future

### funded_by

Erasmus+ Programme – Strategic Partnership - Project Nr: 2021-1-CY02-KA220-YOU-000029171

### recommendations

Entrepreneurship

