## GREENOVET
### Description

GREENOVET is an international project that fosters the development of Vocational Education and Training (VET) Excellence in Green Innovation across Europe by establishing Centres of Vocational Excellence (CoVEs). These CoVEs enable an innovative, inclusive, and sustainable economy. They focus the knowledge, resources, and infrastructures of key stakeholders on developing innovation and skills ecosystems, contributing to regional development, and promoting environmental, social, and economic growth in Europe through green and sustainable innovation processes enabled by VET Excellence.

### Type of Initiative

Project

### Provider

GREENOVET

### Creator

Austria (Styria): FH Joanneum Gesellschaft mbH, Technische Universität Graz, 3s Unternehmensberatung GmbH, Green Tech Valley Cluster GmbH, HTBLuVA Graz-Gösting, Wirtschaftskammer Steiermark
Finland (Vaasa): VAASAN YLIOPISTO, VAMIA, Oy Merinova Ab, Ab Yrkeshögsskolan vid Åbo Akademi – Novia
Portugal (Leiria): Instituto Politécnico de Leiria, Pombal Prof – Sociedade de Educação e Ensino Profissional S.A., NERLEI - Associação Empresarial da Região de Leiria
North Macedonia (Skopje): Zdruzenie Nacionalen centar za razvoj na inovacii i pretpriemacko ucenje Skopje, Ss. CYRIL AND METHODIUS UNIVERSITY IN SKOPJE, ASUC Boro Petrushevski, RADE KONCAR - TEP DOOEL Skopje, Macedonian Chambers of Commerce

### description

GREENOVET is an international project that fosters the development of Vocational Education and Training (VET) Excellence in Green Innovation across Europe by establishing Centres of Vocational Excellence (CoVEs). These CoVEs enable an innovative, inclusive, and sustainable economy. They focus the knowledge, resources, and infrastructures of key stakeholders on developing innovation and skills ecosystems, contributing to regional development, and promoting environmental, social, and economic growth in Europe through green and sustainable innovation processes enabled by VET Excellence.

### language

English, German, Finnish, Macedonian, Portuguese, Swedish

### url_initiative

https://www.greenovet.eu/

### target_audience

Students, Teachers

### type

Project

### location

Styria (Austria), Vaasa (Finland), Skopje (North Macedonia), Leiria (Portugal) and online platform 

### content

One objectives is to foster the employability and entrepreneurial readiness of VET students, preparing and connecting them to the labour market.

### creator_name

Austria (Styria): FH Joanneum Gesellschaft mbH, Technische Universität Graz, 3s Unternehmensberatung GmbH, Green Tech Valley Cluster GmbH, HTBLuVA Graz-Gösting, Wirtschaftskammer Steiermark
Finland (Vaasa): VAASAN YLIOPISTO, VAMIA, Oy Merinova Ab, Ab Yrkeshögsskolan vid Åbo Akademi – Novia
Portugal (Leiria): Instituto Politécnico de Leiria, Pombal Prof – Sociedade de Educação e Ensino Profissional S.A., NERLEI - Associação Empresarial da Região de Leiria
North Macedonia (Skopje): Zdruzenie Nacionalen centar za razvoj na inovacii i pretpriemacko ucenje Skopje, Ss. CYRIL AND METHODIUS UNIVERSITY IN SKOPJE, ASUC Boro Petrushevski, RADE KONCAR - TEP DOOEL Skopje, Macedonian Chambers of Commerce

### creator_role

Consortium

### provider_name

GREENOVET

### funded_by

European Partners and co-funded by Erasmus+ Programme of the European Union

### recommendations

- No provided ressources on the website

