## Micro-credential in Sustainability
### Description

The Micro-credential programme consists of 5 MOOCs (Massive Open Online Courses): Introduction to Sustainability, Climate, Biodiversity, Political Economy of Sustainability and Sustainability and the Arts. It is worth 10 ECTS credits in total. The tool and programme was developed by UNA EUROPA, an alliance of 11 European universities for a student own learning path. The Micro-credential is included as a module in the curriculum of the Master’s Programme for Atmospheric Sciences of the University of Helsinki. 

### Type of Initiative

Course

### Provider

UNA EUROPA 

### Creator

KU Leuven, Belgium	
University of Helsinki, Finland
Paris 1 Panthéon-Sorbonne University, France	
Free University of Berlin, Germany	
University College Dublin, Ireland	
University of Bologna, Italy	
Jagiellonian University, Kraków, Poland	
Complutense University of Madrid, Spain	
University of Zurich, Switzerland	
Leiden University, The Netherlands
University of Edinburgh, UK

### description

The Micro-credential programme consists of 5 MOOCs (Massive Open Online Courses): Introduction to Sustainability, Climate, Biodiversity, Political Economy of Sustainability and Sustainability and the Arts. It is worth 10 ECTS credits in total. The tool and programme was developed by UNA EUROPA, an alliance of 11 European universities for a student own learning path. The Micro-credential is included as a module in the curriculum of the Master’s Programme for Atmospheric Sciences of the University of Helsinki. 

### language

English

### url_initiative

https://www.una-europa.eu/study/microcredential-sustainability#content

### resources

Available resources include online materials, textbooks and engaging exercises. 

### url_resources

https://www.una-europa.eu/study/microcredential-sustainability/courses#content

### target_audience

Students, Teachers

### type

Course

### thematic_focus

Sustainable development as a concept, Environmental Education and Awareness, Climate Change Mitigation, Biodiversity Conservation, Policy and Governance, Community Engagement and Outreach, Social and Political Role of Art in the Ecological Crisis 

### green_skill_specificity_level

Transversal, Domain Specific for Arts

### location

Online Mooc

### content

The Micro-credential programme consists of 5 MOOCs 
1. Introduction to Sustainability 3 ECTS
2. Climate.now 2 ECTS
3. Biodiversity.now 2 ECTS
4. Political Economy of Sustainability 2 ECTS
5. Sustainability and the Arts 1 ECTS




### duration

Total duration of the initiative depends on a student own learning path (around 250 hours / 6 weeks)

### cost

The course is free for students of Una Europa partner universities, Climate University, and Biodiversity Education Network. For students outside these institutions - fee apply

### creator_name

KU Leuven, Belgium	
University of Helsinki, Finland
Paris 1 Panthéon-Sorbonne University, France	
Free University of Berlin, Germany	
University College Dublin, Ireland	
University of Bologna, Italy	
Jagiellonian University, Kraków, Poland	
Complutense University of Madrid, Spain	
University of Zurich, Switzerland	
Leiden University, The Netherlands
University of Edinburgh, UK

### creator_role

Consortium

### provider_name

UNA EUROPA 

### contact_email

una.europa@helsinki.fi

### funded_by

European Commission under the Erasmus+ Programme of the European Union; funding from the European Union’s Horizon 2020 Research and Innovation Programme and co-funded by the European Commission under the Erasmus+ Programme's European Universities Initiative.

### recommendations

The course critically discusses the concepts of sustainability, responds to the demands of green transition (including general and transversal skills), offers a flexible way to supplement the degree from any discipline with research-based knowledge (as a module of the masters’ programme). 

