## NBS EduWORLD (Nature-based Solutions Education Network)
### Description

NBS EduWORLD is a Horizon Europe project at the crossroads between nature-based solutions and education, a forerunner project blending the two topics. The result is a unique consortium bringing together researchers, educators, NBS practitioners, and even sports community members with the common goal of creating engaging and locally relevant educational materials centering the environmental, social, and professional merits of NBS.

### Type of Initiative

Project

### Provider

NBS EduWORLD

### Creator

European Schoolnet (EUN), Public Policy and Management Institute (PPMI), ICLEI Europe (ICLEI), Centre for Experiments in Urban Studies (CEUS), The Big Van Theory (TBVT), Ellinogermaniki Agogi (EA), European Football for Development Network (EFDN), The Ministry of Youth and Sports of the Republic of Turkey, Trinity College Dublin (TCD), Association Verde e Moldova (VEM), Almada Municipality (CMA), Horizon Nua (HNUA), Muséum national d'histoire naturelle (MNHN), Municipality of Genoa (CDG), Natural Solutions (NS), Offaly County Council (OCC)


### description

NBS EduWORLD is a Horizon Europe project at the crossroads between nature-based solutions and education, a forerunner project blending the two topics. The result is a unique consortium bringing together researchers, educators, NBS practitioners, and even sports community members with the common goal of creating engaging and locally relevant educational materials centering the environmental, social, and professional merits of NBS.

### language

English

### url_initiative

https://nbseduworld.eu/

### resources

A list of over 200 resources for NBS education and initiatives (including guidance, reports, tools, and services developed around education about NBS).

### url_resources

https://nbseduworld.eu/resources

### target_audience

Students, Teachers

### type

Project

### thematic_focus

Nature-based Solutions, Waste Management, Water Management, Biodiversity Conservation, Urban planning, Green Building, Environmental Education and Awareness, Community Engagement and Outreach.

### green_skill_specificity_level

Transversal

### location

NBS EduWORLD Website

### content

NBS EduWORLD summarise the state of play of NBS education in Europe and evaluate the initiatives already in place, determine how to expand and replicate them and establish a basis and framework for the project itself and future initiatives, resulting in guidance and (policy) recommendations.

### cost

Free

### start_date

September 2022

### end_date

September 2025

### creator_name

European Schoolnet (EUN), Public Policy and Management Institute (PPMI), ICLEI Europe (ICLEI), Centre for Experiments in Urban Studies (CEUS), The Big Van Theory (TBVT), Ellinogermaniki Agogi (EA), European Football for Development Network (EFDN), The Ministry of Youth and Sports of the Republic of Turkey, Trinity College Dublin (TCD), Association Verde e Moldova (VEM), Almada Municipality (CMA), Horizon Nua (HNUA), Muséum national d'histoire naturelle (MNHN), Municipality of Genoa (CDG), Natural Solutions (NS), Offaly County Council (OCC)


### creator_role

Consortium

### provider_name

NBS EduWORLD

### contact_email

info@nbseduworld.eu

### funded_by

European Union - Programme HORIZON (Grant Agreement nº 101060525)

### recommendations

- Nature-based perspective for teaching
- Although adaptable to different teaching levels, more appropriate for primary and secondary education?

