## SENSE
### Description

The SENSE certificate provides training in skills related to the major environmental and societal challenges of our time. These include energy, climate and biodiversity issues, as well as Equality, Diversity and Inclusion (EDI). The systemic nature of environmental and societal problems will be highlighted. This module will also propose possible actions as a student, citizen and future professional.  
The aim of the course is to provide students with structured academic knowledge of these issues, and to help them define their academic career path and future career choices. Successful completion of this module is a prerequisite for the obtention of a diploma at the Université de Lorraine.

### Type of Initiative

Online Course

### Provider

nan

### Creator

Université de Lorraine, France

### description

The SENSE certificate provides training in skills related to the major environmental and societal challenges of our time. These include energy, climate and biodiversity issues, as well as Equality, Diversity and Inclusion (EDI). The systemic nature of environmental and societal problems will be highlighted. This module will also propose possible actions as a student, citizen and future professional.  
The aim of the course is to provide students with structured academic knowledge of these issues, and to help them define their academic career path and future career choices. Successful completion of this module is a prerequisite for the obtention of a diploma at the Université de Lorraine.

### language

French

### url_initiative

https://formations.univ-lorraine.fr/fr/blog/sense-le-module-pour-comprendre-les-enjeux-societaux-et-environnementaux-n46 

### resources

Fact sheet


### url_resources

https://factuel.univ-lorraine.fr/sites/factuel.univ-lorraine.fr/files/files/2024/u31850/fiche_certificat_sense.pdf

### target_audience

Students of the Université de Lorraine

### type

Online Course

### thematic_focus

Renewable energy, Environmental Education and Awareness, Biodiversity

### green_skill_specificity_level

General 

### location

Online platform of the Université de Lorraine (Arche)
CNED platform (https://climat.cned.fr/formations)

### content

 - Semester 1 (6h): Introduction to energy, climate and social issues; Introduction to the challenges of equality, diversity and inclusion (6h) 
 - Semester 3 (12h): Training in fundamental knowledge of climate change and biodiversity, based on the B.A.-BA of Climate and Biodiversity; Complex systems and systems thinking (1) (CNED)  
- Semester 4 (12h): Complex systems and systems thinking (2); Needs, values and responsibilities; In-depth study of Equality, Diversity and Inclusion; Controversies and narratives in the Anthropocene; Towards sustainable development? Case study

### duration

30H (spread over 3 semesters)

### cost

Free and mandatory 

### start_date

September (each year)

### end_date

June (each year)

### creator_name

Université de Lorraine, France

### creator_role

Professor, Sustainability Coordinator 

### contact_name

Guillain MAUVIEL

### contact_email

guillain.mauviel@univ-lorraine.fr

### funded_by

Université de Lorraine, French Minister for Higher Education and Research

### recommendations

- Mandatory for obtention diploma
- Concrete actions as a student, citizen and future professional.  
- Course material not publicly available (exepct B.A.-BA of Climate and Biodiversity from CNED)

