## Sky4.0
### Description

The present project aim is to build curricula and training modules around two specific sets of soft skills development, namely Social Competencies, Character-Building Skills and Personal Development skills, which should provide a base to make relevant positive choices and decisions leading to level-headedness and wholeheartedness workers.

### Type of Initiative

Educational Program, course, Course, Workshop

### Provider

Sky4.0

### Creator

INOVA+ - INNOVATION SERVICES, SA (Portugal) 
Aviation Valley Association (Poland) 
QSR - Talent Driven Culture (Portugal)
INNpuls Sp. z o.o. - (Poland)
Aerospace Cluster Association (Turkey)
The Machine Tool Institute (Spain)
The Technical University of Madrid (Spain) 

### description

The present project aim is to build curricula and training modules around two specific sets of soft skills development, namely Social Competencies, Character-Building Skills and Personal Development skills, which should provide a base to make relevant positive choices and decisions leading to level-headedness and wholeheartedness workers.

### language

English

### url_initiative

https://sky-project.eu/en/

### resources

Curricula for trainers/work, text books for students/workers and implementation guidelines for education and companies. online materials, textbooks, Moodle Platform 

### url_resources

https://sky-project.eu/en/resources/

### target_audience

Students in aerospace industry

### type

Educational Program, course, Course, Workshop

### thematic_focus

Sustainable Transportation, Energy Efficiency, Sustainable Business Practices.

### green_skill_specificity_level

Domain-specific

### location

https://sky-project.eu/en/resources/

### content

Introduction to our courses: Our Approach
How to develop and improve INTELLECTUAL CURIOSITY for aerospace industry 4.0
How to develop and improve INITIATIVE for aerospace industry 4.0
How to develop and improve COGNITIVE FLEXIBILITY for aerospace industry 4.0
How to develop and improve CRITICAL THINKING for aerospace industry 4.0
How to develop and improve CHANGE ADAPTABILITY for aerospace industry 4.0
How to develop and improve ANALITYCAL THINKING for aerospace industry 4.0



### duration

project duration: 01/12/2018 - 31/08/2021 (33 months) 

courses duration: according to the participant pace (approx. 16 hours each training in-class module) 

### cost

Free of charge 


### creator_name

INOVA+ - INNOVATION SERVICES, SA (Portugal) 
Aviation Valley Association (Poland) 
QSR - Talent Driven Culture (Portugal)
INNpuls Sp. z o.o. - (Poland)
Aerospace Cluster Association (Turkey)
The Machine Tool Institute (Spain)
The Technical University of Madrid (Spain) 

### creator_role

Consortium

### provider_name

Sky4.0

### contact_name

https://sky-project.eu/en/team/

### funded_by

European Commission under the Erasmus+ Programme, Cooperation for innovation and the exchange of good practices, Strategic Partnerships for vocational education and training. (2018-1-PL01-KA202-051081)

### funding_amount

362 183,00 €

### recommendations

The resources and courses are designed for a company’s needs (max. 16 hour course) in order to be better prepared for Industry 4.0 by improving the soft skills of their human resources; the exercises are simple and diverse, depending on the skill; although some content is related to aerospace workplace, the majority of content is suitable for transversal skills development for any study area; there are also materials (lessons) for secondary/VET students (targeting Z-generation); for effective and reliable studies of the chosen skills – there are practical guidelines for trainers/coaches with more in-depth approach and time availability.

