## The challenges of the ecological transition
### Description

This book provides a cross-sectional view of the global environmental changes affecting our finite planet. In particular, it aims to provide an understanding of the mechanisms and consequences of global warming and the erosion of biodiversity, and how these relate to our lifestyles and consumption patterns.
It is based on one of the first large-scale digital courses on the ‘Challenges of the ecological transition’, which was taught in 2020 to several thousand undergraduate students from all disciplines at the University of Paris-Saclay.
To meet the book's cross-disciplinary objective, more than forty teacher-researchers and researchers from different backgrounds have contributed, combining knowledge from the natural sciences, the humanities and social sciences, law, economics, management, agronomy and medicine.

### Type of Initiative

Course

### Provider

Université Paris Saclay

### Creator

Sous la direction de Jean-Michel Lourtioz, Jane Lecomte, Sophie Szopa

### description

This book provides a cross-sectional view of the global environmental changes affecting our finite planet. In particular, it aims to provide an understanding of the mechanisms and consequences of global warming and the erosion of biodiversity, and how these relate to our lifestyles and consumption patterns.
It is based on one of the first large-scale digital courses on the ‘Challenges of the ecological transition’, which was taught in 2020 to several thousand undergraduate students from all disciplines at the University of Paris-Saclay.
To meet the book's cross-disciplinary objective, more than forty teacher-researchers and researchers from different backgrounds have contributed, combining knowledge from the natural sciences, the humanities and social sciences, law, economics, management, agronomy and medicine.

### language

French

### url_initiative

https://www.edp-open.org/books/edp-open-books/427-enjeux-de-la-transition-ecologique

### resources

Book

### url_resources

https://www.edp-open.org/images/stories/books/fulldl/9782759826612_Enjeux-Transition-Ecologique_ebook.pdf

### type

Course

### creator_name

Sous la direction de Jean-Michel Lourtioz, Jane Lecomte, Sophie Szopa

### provider_name

Université Paris Saclay

### funded_by

This work benefited from financial support from the program
“Investissement d'Avenir”.

### recommendations

Make accessible this course to everyone 

