## UNIgreen
### Description

UNIgreen is an Alliance of eight Higher Education Institutions focusing specifically on sustainable agriculture, green biotechnology, and environmental and life sciences. They are committed to promoting excellence in education, research and innovation, and that are active in developing knowledge and solutions that give an answer to the needs of local communities.

### Type of Initiative

Project

### Provider

Unigreen

### Creator

University of Modena and Reggio Emilia (Italy)
University of Almería (Spain)
Haute Ecole de la Province de Liège (Belgium)
Warsaw University of Life Sciences (Poland)
Polytechnic University of Coimbra (Portugal)
University of Plovdiv (Bulgaria)
Agricultural University of Iceland (Iceland)
Sup’Bioptech Engineering School of Biotechnology (France)

### description

UNIgreen is an Alliance of eight Higher Education Institutions focusing specifically on sustainable agriculture, green biotechnology, and environmental and life sciences. They are committed to promoting excellence in education, research and innovation, and that are active in developing knowledge and solutions that give an answer to the needs of local communities.

### language

English

### url_initiative

https://unigreen-alliance.eu/

### url_resources

https://unigreen-alliance.eu/education/unigreen-courses/#courses-for-students
https://unigreen-alliance.eu/virtual-campus/


### target_audience

Students, Teachers, Staff

### type

Project

### location

unigreen website and universities

### content

Specific agreements among these institutions facilitate the implementation of mobility actions. A significant outcome combining teaching and innovative, high-level research is the launch of a joint PhD program in Agro-Food Sciences, Technologies, and Biotechnologies starting from the academic year 2024-2025. This PhD program will award the degree from five universities (University of Modena and Reggio Emilia, Almería, Coimbra, Plovdiv, and Iceland). Additionally, joint programs for awarding dual or multiple degrees are being planned, which will further open up international opportunities through first and second-level educational paths. These programs will include lectures and seminars in shared virtual classrooms among the Alliance universities, participation in Summer Schools, Blended Intensive Programs (BIPs), and other educational activities that will occur both in-person and remotely in a lifelong learning context.

### creator_name

University of Modena and Reggio Emilia (Italy)
University of Almería (Spain)
Haute Ecole de la Province de Liège (Belgium)
Warsaw University of Life Sciences (Poland)
Polytechnic University of Coimbra (Portugal)
University of Plovdiv (Bulgaria)
Agricultural University of Iceland (Iceland)
Sup’Bioptech Engineering School of Biotechnology (France)

### provider_name

Unigreen

### funded_by

Funded by the European Union.

### recommendations

The core of the UNIgreen Virtual Campus will be the e-learning platform based on LMS Blackboard. 

