## University Green Digital HUB
### Description

The main goal of the project University Green Digital HUB is to develop and advance digital, green and entrepreneurial (DGE) skills of students, staff and university startups through re- and upskilling DGE programs and startup support program in green and digital innovation. Students will be able to get Europass digital credentials and/or diploma supplements for completion of courses.

### Type of Initiative

nan

### Provider

University Green Digital HUB

### Creator

University of Split (Croatia), University of Malaga (Spain) and Stuttgart Media University (Germany), Impact HUB Stuttgart (Germany), Split Entrepreneurship Centre (Croatia) and Preneurz.Amsterdam (Netherlands).

### description

The main goal of the project University Green Digital HUB is to develop and advance digital, green and entrepreneurial (DGE) skills of students, staff and university startups through re- and upskilling DGE programs and startup support program in green and digital innovation. Students will be able to get Europass digital credentials and/or diploma supplements for completion of courses.

### language

English, Croatian, Spanish, German, Dutch

### url_initiative

https://www.ugd-hub.com/

### resources

Mooc

### url_resources

https://e-learning.ugd-hub.com/

### content

Green skills:
- Acting for Sustainability
- Envisioning sustainable futures
- Measuring the Impact of startup programs

### creator_name

University of Split (Croatia), University of Malaga (Spain) and Stuttgart Media University (Germany), Impact HUB Stuttgart (Germany), Split Entrepreneurship Centre (Croatia) and Preneurz.Amsterdam (Netherlands).

### provider_name

University Green Digital HUB

### contact_email

spi@efst.hr

### funded_by

This project has been funded with support from the European Commission.

