name: 📚 Compile and Publish Website

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build:
    name: 📦 Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 🛠️ Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: 🎨 Render
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: 📦 Compress
        run: tar -cvf _site.tar.gz _site/

      - name: ⬆️ Upload
        uses: actions/upload-artifact@v4
        with:
          name: _site.tar.gz
          path: _site.tar.gz
          retention-days: 1

  deploy:
    name: 🚀 Deploy
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # for trusted publishing
      pages: write
      contents: read
    steps:
      - name: ⬇️ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: _site.tar.gz
      - name: 📦 Unpack
        run: tar -xvf _site.tar.gz
      - name: 🛠️ Setup Pages
        uses: actions/configure-pages@v5
      - name: ⬆️ Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site/
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4